name: Terraform

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #AWS_DEFAULT_REGION: ap-southeast-1

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
             
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Create demo workspace
        id: workspace
        run: terraform workspace new demo
        continue-on-error: true        

      - name: Select demo workspace
        id: select
        run: terraform workspace select demo
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
